# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a50dd326288003c3199809028f3a6fbc356612bea8ba7ed98a834b09a1c618a75a45c5358fbf0d80f8e80c6f290f45c815a5da29f03a9d7cce8a70f78fc0be76

test:
  secret_key_base: 0feb007d0b5e176f4933e7b7098d4ccc34243484b22fc75724102a3a7f8669319f88fb9226f3be272a089fbef7cbac7c1e3420c1e16d9ad4851b1b450bf2171c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
